# Generated by Django 6.0.2 on 2026-02-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
