# Generated by Django 6.0.2 on 2026-02-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_details_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('fathername', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobilenumber', models.CharField(max_length=20)),
            ],
        ),
    ]
